version: '3.6'

services:

  # Backend
  smart-brain-api:
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/smart-brain-api
    command: npm start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URI: postgres://admin:password@postgres:5432/smart-brain-docker
    links:
      - postgres

   # PostgreSQL
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
